language: c
sudo: false

env:
  matrix:
    - LUA=lua5.1
    - LUA=luajit

branches:
  only: master

before_install:
  - source .travis.sh

install: luarocks install *.rockspec --only-deps

script: busted
